name: Build and Deploy API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t tineship/tradeapi:latest -f trade.API/Dockerfile .

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
    - name: Tag docker image
      run: docker tag tineship/tradeapi:latest tineship/tradeapi:latest
      
    - name: Push Docker image
      run: docker push tineship/tradeapi:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH to Server and Deploy
      run: |
        sudo apt-get update && sudo apt-get install -y sshpass
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${USER}@${{ secrets.SERVER_HOST }} << 'EOF'
          # Commands to execute on the server
          docker pull myapi:latest
          docker stop myapi || true
          docker rm myapi || true
          docker run -d -p 80:80 --name myapi myapi:latest
        EOF
      env:
        USER: root
