name: Build, Push Docker Image, and Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./trade.API/Dockerfile
        push: true
        tags: tineship/tradepro:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: ${{ secrets.VM_PORT }}
        script: |
          docker pull ${{ secrets.DOCKER_REPONAME }}/tradepro:latest
          docker stop your-container-name || true
          docker rm your-container-name || true
          docker run -d --name your-container-name -p 8081:8081 ${{ secrets.DOCKER_REPONAME }}/tradepro:latest